/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_MAX_PLAYERS: process.env.NEXT_PUBLIC_MAX_PLAYERS,
    NEXT_PUBLIC_DEFAULT_DISCUSSION_TIME: process.env.NEXT_PUBLIC_DEFAULT_DISCUSSION_TIME,
    NEXT_PUBLIC_DEFAULT_MAX_ROUNDS: process.env.NEXT_PUBLIC_DEFAULT_MAX_ROUNDS,
    NEXT_PUBLIC_DEFAULT_TIME_PER_ROUND: process.env.NEXT_PUBLIC_DEFAULT_TIME_PER_ROUND,
    NEXT_PUBLIC_DEFAULT_VOTING_TIME: process.env.NEXT_PUBLIC_DEFAULT_VOTING_TIME,
  },
}

module.exports = nextConfig 